In [5]:
import pandas as pd

csv_df = pd.read_csv("cars.csv", delimiter=";")
csv_df.head()

Car   MPG  Cylinders  Displacement  Horsepower  \
0  Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1          Buick Skylark 320  15.0          8         350.0       165.0   
2         Plymouth Satellite  18.0          8         318.0       150.0   
3              AMC Rebel SST  16.0          8         304.0       150.0   
4                Ford Torino  17.0          8         302.0       140.0   

   Weight  Acceleration  Model Origin  
0  3504.0          12.0     70     US  
1  3693.0          11.5     70     US  
2  3436.0          11.0     70     US  
3  3433.0          12.0     70     US  
4  3449.0          10.5     70     US

In [6]:
import numpy as np
a = np.array([[1, 2, 3,], [4, 5, 6]], dtype=np.float32)
print(a.ndim, a.shape, a.dtype) 

2 (2, 3) float32


2 (2, 3)


In [23]:
c = np.array([[1, 2, 3,], [4, 5, 6]], dtype=np.float32)
print(a.ndim, a.shape)

2 (2, 3)


In [22]:
x = np.ones((3, 2))
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [25]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [27]:
a = a.reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
a = a.reshape(2, -1)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [40]:
b = np.arange(10).reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
b = b.T
b

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [42]:
b = b.transpose([1,0])
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
np.sqrt(b)

array([[0.        , 1.        ],
       [1.41421356, 1.73205081],
       [2.        , 2.23606798],
       [2.44948974, 2.64575131],
       [2.82842712, 3.        ]])