### Homework 3 Numpy Arrays and Pandas

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into a numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [20]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. (2 pts) What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [21]:
print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)
print(origin.dtype)

object
float64
float64
object


2. (1 pt) `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [22]:
# the action is aliasing
# you might do this for simplicity and consistency whenever you call a numpy function

3. (2 pts) Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [23]:
for i in df.columns:
    print(df[i].ndim)

1
1
1
1
1
1
1
1
1


4. (3 pts) What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help) (1 pt extra credit)

In [24]:
hp_sum = df[["Horsepower"]].sum()
hp_min = df[["Horsepower"]].min()
hp_max = df[["Horsepower"]].max()
hp_median = df[["Horsepower"]].median()
hp_mode = df[["Horsepower"]].mode()

hp_sum, hp_min, hp_max, hp_median, hp_mode     

(Horsepower    42033.0
 dtype: float64,
 Horsepower    0.0
 dtype: float64,
 Horsepower    230.0
 dtype: float64,
 Horsepower    93.5
 dtype: float64,
    Horsepower
 0       150.0)

5. (2 pts) Select the last element in each subarray (do this with one operation.)

In [25]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [26]:
last_columns = select_more[ :, -1 ]
last_columns

array([3, 6, 9])

6. (2 pts) Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [56]:
# np.lookfor doesnt exist past numpy v2.0
np.log(mpg)

/var/folders/lj/hkhcwb916w11w9xnvrlgd9nw0000gn/T/ipykernel_6767/67066281.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(mpg)


array([2.89037176, 2.7080502 , 2.89037176, 2.77258872, 2.83321334,
       2.7080502 , 2.63905733, 2.63905733, 2.63905733, 2.7080502 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       2.7080502 , 2.63905733,       -inf, 2.7080502 , 2.63905733,
       3.17805383, 3.09104245, 2.89037176, 3.04452244, 3.29583687,
       3.25809654, 3.21887582, 3.17805383, 3.21887582, 3.25809654,
       3.04452244, 2.30258509, 2.30258509, 2.39789527, 2.19722458,
       3.29583687, 3.33220451, 3.21887582, 3.21887582,       -inf,
       2.94443898, 2.77258872, 2.83321334, 2.94443898, 2.89037176,
       2.63905733, 2.63905733, 2.63905733, 2.63905733, 2.48490665,
       2.56494936, 2.56494936, 2.89037176, 3.09104245, 2.94443898,
       2.89037176, 3.13549422, 3.33220451, 3.40119738, 3.40119738,
       3.4339872 , 3.55534806, 3.29583687, 3.25809654, 3.17805383,
       3.21887582, 3.13549422, 2.99573227, 3.04452244, 2.56494936,
       2.63905733, 2.7080502 , 2.63905733, 2.83321334, 2.39789

7. (2 pts) Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [49]:
us_bool = df['Origin'] == 'US'
origin_bool

0       True
1       True
2       True
3       True
4       True
       ...  
401     True
402    False
403     True
404     True
405     True
Name: Origin, Length: 406, dtype: bool

8. (2 pts) Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [51]:
car[origin_bool]

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

### Use numpy or pandas to answer the following questions.

9. (3 pts) What is the average horsepower for `Europe` cars? (Hint: create a boolean index of 'US' apply it to horsepower and perform the calculation.)

In [54]:
eu_bool = df['Origin'] == 'Europe'
horsepower[eu_bool].mean()
# 78.78082191780823

np.float64(78.78082191780823)

10. (3 pts) On average are Japanese cars more fuel-efficient than US cars? Show the code that you used to determine this.  

In [28]:
country_df = df.set_index('Origin')

jp_df = country_df.loc[['Japan'], : ]
jp_mileage = jp_df[['MPG']].mean()

us_df = country_df.loc[['US'], : ]
us_mileage = us_df[['MPG']].mean()

us_mileage, jp_mileage # 19.688189 < 30.450633 -> japanese cars are more fuel-efficient

(MPG    19.688189
 dtype: float64,
 MPG    30.450633
 dtype: float64)

11. (3 pts) What is the correlation coefficient of `mpg` and `weight`? What is a correlation coefficient? What does the result indicate about the relationship between mpg and weight? 

In [43]:
correlation = np.corrcoef(mpg, weight)
correlation

# the correlation coefficient is -0.78750994
# the corrcoef is the strength of the linear relationship between two variables
# the result indicates a strong inverse relationship between mpg and weight, heavier cars are less fuel efficient and vice versa

array([[ 1.        , -0.78750994],
       [-0.78750994,  1.        ]])

Extra credit: (3 pts) Create a new pandas dataframe that has the average mpg, weight, and horsepower per country of origin

In [31]:
origin_df = df.groupby('Origin')

avg_mpg = origin_df[['MPG']].mean()
avg_weight = origin_df[['Weight']].mean()
avg_hp = origin_df[['Horsepower']].mean()

merged = pd.merge(avg_mpg, avg_weight, on='Origin')  
final_df = pd.merge(merged, avg_hp, on='Origin')  

final_df

MPG       Weight  Horsepower
Origin                                    
Europe  26.745205  2431.493151   78.780822
Japan   30.450633  2221.227848   79.835443
US      19.688189  3372.700787  118.011811